steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.prod', '-t', 'asia-east1-docker.pkg.dev/days-gemini/eighty-days-api-img/eighty-days-api-img:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-east1-docker.pkg.dev/days-gemini/eighty-days-api-img/eighty-days-api-img:latest']