apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: eighty-days-api-service
spec:
  template:
    spec:
      serviceAccountName: gh-80-days-gemini@days-gemini.iam.gserviceaccount.com
      containers:
        - image: asia-east1-docker.pkg.dev/days-gemini/eighty-days-api-img/eighty-days-api-img:latest
          ports:
            - containerPort: 8000
          env:
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: GEMINI_API_KEY
                  key: latest
            - name: GEMINI_MODEL
              valueFrom:
                secretKeyRef:
                  name: GEMINI_MODEL
                  key: latest
            - name: FIREBASE_DB_NAME 
              valueFrom:
                secretKeyRef:
                  name: FIREBASE_DB_NAME 
                  key: latest
            - name: USERS_COLLECTION 
              valueFrom:
                secretKeyRef:
                  name: USERS_COLLECTION 
                  key: latest
            - name: GAME_SAVES_COLLECTION 
              valueFrom:
                secretKeyRef:
                  name: GAME_SAVES_COLLECTION 
                  key: latest
            - name: FIRESTORE_PROJECT_ID 
              valueFrom:
                secretKeyRef:
                  name: FIRESTORE_PROJECT_ID 
                  key: latest
            