apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: eighty-days-api-service
spec:
  template:
    spec:
      containers:
        - image: asia-east1-docker.pkg.dev/days-gemini/eighty-days-api-img/eighty-days-api-img:latest
          ports:
            - containerPort: 8000
          env:
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: GEMINI_API_KEY
                  key: latest
            - name: GEMINI_MODEL
              valueFrom:
                secretKeyRef:
                  name: GEMINI_MODEL
                  key: latest