name: CI/CD Pipeline

env:
  SERVICE_NAME: eighty-days-api-service
  PROJECT_ID: days-gemini
  DOCKER_IMAGE_URL: asia-east1-docker.pkg.dev/days-gemini/eighty-days-api-img/eighty-days-api-img

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  secret-scanning:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch all tags
        run: git fetch --tags

      - name: Run gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  dockerize-and-deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: secret-scanning

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCR_SA_KEY }}'
          project_id: ${{ env.PROJECT_ID }}

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Configure Docker
        run: |
          gcloud auth configure-docker asia-east1-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE_URL }}:latest -f Dockerfile.prod .
          docker push ${{ env.DOCKER_IMAGE_URL }}:latest

      - name: Deploy to Cloud Run
        run: |
          echo SERVICE_NAME $SERVICE_NAME
          gcloud run services replace service.yaml \
          --region asia-east1
